import { GetTodoListItemByIdUseCase, AddNewListItemUseCase, AddNewTodoListUseCase, CreateNewUserUseCase, DeleteListItemUseCase, DeleteTodoListUseCase, GetTodoListByIdUseCase, LoginUserUseCase, LogoutUserUseCase, UpdateListItemUseCase, UpdateUserProfileUseCase, GetAllTodoListsUseCase } from '@core/domain-logic';
declare const addNewTodoList: AddNewTodoListUseCase;
declare const deleteTodoList: DeleteTodoListUseCase;
declare const getAllTodoLists: GetAllTodoListsUseCase;
declare const getTodoListById: GetTodoListByIdUseCase;
declare const addNewListItem: AddNewListItemUseCase;
declare const deleteListItem: DeleteListItemUseCase;
declare const updateListItem: UpdateListItemUseCase;
declare const getTodoListItemById: GetTodoListItemByIdUseCase;
declare const logoutUser: LogoutUserUseCase;
declare const updateUserProfile: UpdateUserProfileUseCase;
declare const loginUser: LoginUserUseCase;
declare const createNewUser: CreateNewUserUseCase;
export { getTodoListItemById, addNewListItem, addNewTodoList, deleteListItem, deleteTodoList, getTodoListById, updateListItem, getAllTodoLists, logoutUser, updateUserProfile, loginUser, createNewUser };
