export enum Filter {
    ALL_LIST_ITEMS = 'ALL_LIST_ITEMS',
    COMPLETE_LIST_ITEMS = 'COMPLETE_LIST_ITEMS',
    INCOMPLETE_LIST_ITEMS = 'INCOMPLETE_LIST_ITEMS'
}

export enum CompleteState {
    COMPLETED = 'COMPLETED',
    INCOMPLETE = 'INCOMPLETE'
}