export enum ListItemStatus {
    COMPLETED = 'COMPLETED',
    INCOMPLETE = 'INCOMPLETE'
}

export enum Filter {
    ALL_LIST_ITEMS = 'ALL_LIST_ITEMS',
    COMPLETE_LIST_ITEMS = 'COMPLETE_LIST_ITEMS',
    INCOMPLETE_LIST_ITEMS = 'INCOMPLETE_LIST_ITEMS'
}

export enum FormType {
    NEW_TODOLIST = 'NEW_TODOLIST',
    NEW_TODOLIST_ITEM = 'NEW_TODOLIST_ITEM'
}

export enum Visibility {
    VISIBLE = 'VISIBLE',
    INVISIBLE = 'INVISIBLE'
}

