interface ContainerStyleProps {
    height?: string;
    maxHeight?: string;
    width?: string;
    maxWidth?: string;
    background?: string;
    display?: string;
    flexDirection?: string;
    justifyContent?: string;
    alignItems?: string;
    padding?: string;
    pt?: string;
    pb?: string;
    pl?: string;
    pr?: string;
    mb?: string;
    mt?: string;
    mr?: string;
    ml?: string;
    flexGrow?: string;
    flexShrink?: string;
    flexBasis?: string;
    gap?: string;
    fontFamily?: string;
    boxSizing?: string;
    borderRadius?: string;
    elevation?: string;
    border?: string;
    overflow?: string;
    overflowx?: string;
    overflowy?: string;
    flex?: string;
}
export type { ContainerStyleProps };
